name: Release to PyPI

on:
  push:
    tags:
      - '*'

jobs:
  deploy:
    name: Deploy package to PYPI
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10']
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run build
        run: pipx run build --sdist --wheel
      - name: publish
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_PWD }}
        run: |
          pipx install twine
          twine upload --skip-existing dist/*
